// src/pages/auth/TwoFactorAuth.tsx

import { useState, useEffect, useRef } from "react";
import { useNavigate } from "react-router-dom";
import { Logo } from "@/components/Logo";
import { AnimatedGradientBackground } from "@/components/AnimatedGradientBackground";
import { Button } from "@/components/ui/button";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { InputOTP, InputOTPGroup, InputOTPSlot } from "@/components/ui/input-otp";

const TwoFactorAuth = () => {
  const navigate = useNavigate();
  const [value, setValue] = useState("");
  const [error, setError] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  // Token guard - redirect to login if no temp token
  useEffect(() => {
    const tempToken = sessionStorage.getItem('twofa_temp_token');
    if (!tempToken) {
      navigate('/login', { replace: true });
    }

    // Clean up any lingering query params
    try {
      window.history.replaceState(null, '', window.location.pathname);
    } catch (err) {
      console.error('Failed to clean URL:', err);
    }
  }, [navigate]);

  // Handle form submission
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (value.length !== 6) {
      setError('Enter a valid 6-digit code');
      return;
    }

    const user_id = sessionStorage.getItem('pending_2fa_user_id');
    if (!user_id) {
      setError('Session expired. Please log in again.');
      setTimeout(() => navigate('/login', { replace: true }), 2000);
      return;
    }

    setError("");
    setIsLoading(true);

    try {
      const res = await fetch('https://api.modovisa.com/api/verify-2fa-login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({ 
          user_id, 
          code: value 
        })
      });

      const result = await res.json().catch(() => ({}));

      if (!res.ok) {
        setIsLoading(false);
        setError(result.error || 'Invalid or expired code.');
        return;
      }

      // Cache display name for UI (non-fatal)
      try {
        const displayName = result.username || 
                           result.name || 
                           (result.email ? result.email.split('@')[0] : 'User');
        localStorage.setItem('username', displayName);
      } catch (err) {
        console.error('Failed to cache username:', err);
      }

      // Clean up session storage
      sessionStorage.removeItem('twofa_temp_token');
      sessionStorage.removeItem('pending_2fa_user_id');

      // Redirect to dashboard
      navigate('/app/live-tracking', { replace: true });

    } catch (err) {
      console.error('❌ 2FA verification error:', err);
      setIsLoading(false);
      setError('Unexpected error during verification.');
    }
  };

  // Auto-submit when 6 digits entered
  useEffect(() => {
    if (value.length === 6 && !isLoading) {
      handleSubmit(new Event('submit') as any);
    }
  }, [value]);

  return (
    <AnimatedGradientBackground layout="full">
      <div className="w-full max-w-md glass-card rounded-3xl shadow-2xl p-8 space-y-6">
        <div className="flex flex-col items-center space-y-2">
          <Logo showBeta={false} />
          <p className="text-lg font-semibold">Intuitive Analytics.</p>
          <h1 className="text-2xl font-semibold mt-6">Two Step Verification</h1>
          <p className="text-center text-muted-foreground text-sm">
            Enter the code generated by your authenticator app.
          </p>
        </div>

        {isLoading && (
          <div className="text-center py-4">
            <div className="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
            <p className="mt-2 text-sm text-muted-foreground">Verifying your code...</p>
          </div>
        )}

        <form className="space-y-6" onSubmit={handleSubmit}>
          <div className="space-y-4">
            <label className="text-sm font-medium text-center block">
              Type your 6 digit authentication code
            </label>
            
            <div className="flex justify-center">
              <InputOTP 
                maxLength={6} 
                value={value}
                onChange={(value) => setValue(value)}
                disabled={isLoading}
              >
                <InputOTPGroup>
                  <InputOTPSlot index={0} className="h-14 w-14 text-lg" />
                  <InputOTPSlot index={1} className="h-14 w-14 text-lg" />
                  <InputOTPSlot index={2} className="h-14 w-14 text-lg" />
                  <InputOTPSlot index={3} className="h-14 w-14 text-lg" />
                  <InputOTPSlot index={4} className="h-14 w-14 text-lg" />
                  <InputOTPSlot index={5} className="h-14 w-14 text-lg" />
                </InputOTPGroup>
              </InputOTP>
            </div>
          </div>

          {error && (
            <Alert variant="destructive">
              <AlertDescription>{error}</AlertDescription>
            </Alert>
          )}

          <Button 
            className="w-full h-12 text-base" 
            size="lg"
            type="submit"
            disabled={isLoading || value.length !== 6}
          >
            {isLoading ? 'Verifying...' : 'Verify my account'}
          </Button>
        </form>
      </div>
    </AnimatedGradientBackground>
  );
};

export default TwoFactorAuth;