import { Logo } from "@/components/Logo";
import { Button } from "@/components/ui/button";
import { InputOTP, InputOTPGroup, InputOTPSlot } from "@/components/ui/input-otp";

const TwoFactorAuth = () => {
  return (
    <div className="min-h-screen gradient-primary flex items-center justify-center p-4">
      <div className="w-full max-w-md glass-card rounded-3xl shadow-2xl p-8 space-y-6">
        <div className="flex flex-col items-center space-y-2">
          <Logo />
          <h1 className="text-2xl font-semibold mt-6">Two Step Verification</h1>
          <p className="text-center text-muted-foreground text-sm">
            Enter the code generated by your authenticator app.
          </p>
        </div>

        <form className="space-y-6">
          <div className="space-y-4">
            <label className="text-sm font-medium text-center block">
              Type your 6 digit authentication code
            </label>
            <div className="flex justify-center">
              <InputOTP maxLength={6}>
                <InputOTPGroup>
                  <InputOTPSlot index={0} className="h-14 w-14 text-lg" />
                  <InputOTPSlot index={1} className="h-14 w-14 text-lg" />
                  <InputOTPSlot index={2} className="h-14 w-14 text-lg" />
                  <InputOTPSlot index={3} className="h-14 w-14 text-lg" />
                  <InputOTPSlot index={4} className="h-14 w-14 text-lg" />
                  <InputOTPSlot index={5} className="h-14 w-14 text-lg" />
                </InputOTPGroup>
              </InputOTP>
            </div>
          </div>

          <Button className="w-full h-12 text-base" size="lg">
            Verify my account
          </Button>
        </form>
      </div>
    </div>
  );
};

export default TwoFactorAuth;
